name: Download R binaries

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("stringr")'

    - name: Run R script
      run: Rscript dl_script.R
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Download binaries"
        add: "./R-binaries"