name: Install package from binary

on:
  workflow_dispatch:

# jobs:
#   run-script:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Install dependencies
#       uses: r-lib/actions/setup-r@v2
    
#     - run: |