name: Download R binaries - R ver

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: r-lib/actions/setup-r@v2
    
    - run: |
        Rscript -e 'install.packages("stringr")'

    - name: Run R script
      run: Rscript ./R-binaries/dl_script.R

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Download binaries"
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        add: "./R-binaries"